[programs.localnet]
x_staking = "9XrdGhMegRkXfTYPiMpBkPjHmJjxexbriLKVJo5vXDo3"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "test-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/x-test.ts"
